"""add incident embedding

Revision ID: 29be0a0b9c3c
Revises: 4cc93d1692fb
Create Date: 2026-06-23 11:29:17.206758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29be0a0b9c3c'
down_revision: Union[str, Sequence[str], None] = '4cc93d1692fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'action_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('incident', sa.Column('service', sa.Text(), nullable=False))
    op.add_column('incident', sa.Column('matrics_summary', sa.Text(), server_default='', nullable=False))
    op.add_column('incident', sa.Column('embedding', Vector(768), nullable=True))
    op.alter_column('incident', 'rawAlert',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_incident_alert_name'), 'incident', ['alert_name'], unique=False)
    op.create_index(op.f('ix_incident_instance'), 'incident', ['instance'], unique=False)
    op.create_index(op.f('ix_incident_receivedAt'), 'incident', ['receivedAt'], unique=False)
    op.create_index(op.f('ix_incident_service'), 'incident', ['service'], unique=False)
    op.drop_column('incident', 'matric_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('matric_summary', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incident_service'), table_name='incident')
    op.drop_index(op.f('ix_incident_receivedAt'), table_name='incident')
    op.drop_index(op.f('ix_incident_instance'), table_name='incident')
    op.drop_index(op.f('ix_incident_alert_name'), table_name='incident')
    op.alter_column('incident', 'rawAlert',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('incident', 'embedding')
    op.drop_column('incident', 'matrics_summary')
    op.drop_column('incident', 'service')
    op.alter_column('actions', 'action_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
